2020-05-20 16:37:42,800 ERROR 17757 nodejs.SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Promise.tap.then.catch.err (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/dialects/mysql/connection-manager.js:123:19)
    at tryCatcher (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/async.js:15:14)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/debuggability.js:482:19)
    at Function.Promise.attempt.Promise.try (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/method.js:29:9)
    at Sequelize.query (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/sequelize.js:580:23)
    at Sequelize.authenticate (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/sequelize.js:892:17)
    at authenticate (/Users/jianghui/Code/my_code/whisky-app/node_modules/_egg-sequelize@5.2.1@egg-sequelize/lib/loader.js:134:22)
    at authenticate (/Users/jianghui/Code/my_code/whisky-app/node_modules/_egg-sequelize@5.2.1@egg-sequelize/lib/loader.js:142:13)
name: "SequelizeConnectionRefusedError"
parent: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
original: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
pid: 17757
hostname: jianghuideMacBook-Pro.local

2020-05-20 16:53:46,958 ERROR 19814 nodejs.SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/dialects/mysql/query.js:223:16)
    at Execute.handler [as onResult] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/Users/jianghui/Code/my_code/whisky-app/node_modules/_mysql2@2.1.0@mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/jianghui/Code/my_code/whisky-app/node_modules/_mysql2@2.1.0@mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_mysql2@2.1.0@mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/jianghui/Code/my_code/whisky-app/node_modules/_mysql2@2.1.0@mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/jianghui/Code/my_code/whisky-app/node_modules/_mysql2@2.1.0@mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/debuggability.js:482:19)
    at Promise._then (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:261:17)
    at Promise.then (/Users/jianghui/Code/my_code/whisky-app/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:154:17)
    at model.save (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/model.js:3964:8)
    at Function.create (/Users/jianghui/Code/my_code/whisky-app/node_modules/_sequelize@5.21.10@sequelize/lib/model.js:2228:8)
    at AppController.create (/Users/jianghui/Code/my_code/whisky-app/app/controller/app.ts:29:24)
name: "SequelizeUniqueConstraintError"
errors: [{"message":"apps.appname must be unique","type":"unique violation","path":"apps.appname","value":"test1","origin":"DB","instance":{"id":null,"appname":"test1","des":"111","appid":"BuSZEZxmro","updatedAt":"2020-05-20T08:53:46.917Z","createdAt":"2020-05-20T08:53:46.917Z"},"validatorKey":"not_unique","validatorName":null,"validatorArgs":[]}]
fields: {"apps.appname":"test1"}
parent: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry 'test1' for key 'apps.appname'","sql":"INSERT INTO `apps` (`id`,`appid`,`appname`,`des`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?,?);","parameters":["BuSZEZxmro","test1","111","2020-05-20 08:53:46","2020-05-20 08:53:46"]}
original: {"code":"ER_DUP_ENTRY","errno":1062,"sqlState":"23000","sqlMessage":"Duplicate entry 'test1' for key 'apps.appname'","sql":"INSERT INTO `apps` (`id`,`appid`,`appname`,`des`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?,?);","parameters":["BuSZEZxmro","test1","111","2020-05-20 08:53:46","2020-05-20 08:53:46"]}
sql: "INSERT INTO `apps` (`id`,`appid`,`appname`,`des`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?,?);"
pid: 19814
hostname: jianghuideMacBook-Pro.local

2020-05-20 16:55:08,605 ERROR 20000 [-/172.18.252.34/-/57ms POST /api/app/create] nodejs.AssertionError [ERR_ASSERTION]: status code must be a number
    at Object.set status [as status] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_koa@2.12.0@koa/lib/response.js:86:5)
    at Object.status (/Users/jianghui/Code/my_code/whisky-app/node_modules/_delegates@1.0.0@delegates/index.js:92:31)
    at Helper.exports.error (/Users/jianghui/Code/my_code/whisky-app/app/extend/helper.js:41:13)
    at AppController.create (/Users/jianghui/Code/my_code/whisky-app/app/controller/app.ts:22:23)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: false
expected: true
operator: "=="
pid: 20000
hostname: jianghuideMacBook-Pro.local

2020-05-20 16:55:28,385 ERROR 20000 [-/172.18.252.34/-/15ms POST /api/app/create] nodejs.AssertionError [ERR_ASSERTION]: status code must be a number
    at Object.set status [as status] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_koa@2.12.0@koa/lib/response.js:86:5)
    at Object.status (/Users/jianghui/Code/my_code/whisky-app/node_modules/_delegates@1.0.0@delegates/index.js:92:31)
    at Helper.exports.error (/Users/jianghui/Code/my_code/whisky-app/app/extend/helper.js:41:13)
    at AppController.create (/Users/jianghui/Code/my_code/whisky-app/app/controller/app.ts:22:23)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: false
expected: true
operator: "=="
pid: 20000
hostname: jianghuideMacBook-Pro.local

2020-05-20 20:31:22,162 ERROR 23161 nodejs.ClusterClientNoResponseError: client no response in 7210882ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 23161
hostname: jianghuideMacBook-Pro.local

2020-05-21 06:32:23,789 ERROR 23161 nodejs.ClusterClientNoResponseError: client no response in 36061605ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 23161
hostname: jianghuideMacBook-Pro.local

2020-05-21 09:59:42,451 ERROR 23161 nodejs.ClusterClientNoResponseError: client no response in 12438635ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/jianghui/Code/my_code/whisky-app/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 23161
hostname: jianghuideMacBook-Pro.local

